# see https://docs.platformio.org/en/latest/integration/ci/travis.html

dist: focal
language: python
python:
  - "3.8.5"

sudo: false
cache:
  pip: true
  directories:
    - $HOME/.platformio
    - $HOME/upy

install:
  - pip install -U platformio invoke
  - pio update
  - URL=https://github.com/micropython/micropython.git
  - if [ ! -d ~/upy/mpy-cross ]; then git clone --depth 1 -b v1.13 $URL ~/upy; fi
  - make -C ~/upy/mpy-cross/
  - export PATH=$PATH:$HOME/upy/mpy-cross

script:
  - pio run -e native -s
  - mpy-cross valid/features.py
  - .pio/build/native/program valid/features.mpy
  - pio test -e native
  - inv -l
  - inv native
  - inv python
