# using Ubuntu 20.04 and the generic image, which has Python w/o virtualenv

os: linux
dist: focal
language: generic

cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.platformio
    - $HOME/mpy

install:
  # tool setup: pio & inv
  - pip3 install -U platformio invoke
  - pio update
  - pio system info

  # build mpy-cross
  - MPY=~/mpy/mpy-cross
  - URL=https://github.com/micropython/micropython.git
  - if [ ! -d $MPY ]; then git clone --depth 1 -b v1.14 $URL ~/mpy; fi
  - make -C $MPY
  - export PATH=$PATH:$MPY
  - inv health

script:
  # expand code generator directives
  - inv generate

  # quick native checks
  - pio run -e native -s
  - mpy-cross test/py/hello.py
  - .pio/build/native/program test/py/hello.mpy

  # native invoke tasks
  - inv test
  - inv python -i gcoll

  # embedded builds
  - inv builds
  - inv examples
