# using Ubuntu 20.04 and the generic image, which has Python w/o virtualenv

dist: focal
language: generic

sudo: false
cache:
  pip: true
  directories:
    - $HOME/.platformio
    - $HOME/mpy

install:
  # tool setup: pio & inv
  - pip3 --version
  - pip3 install -U platformio invoke
  - pio update
  - pio system info

  # build mpy-cross
  - MPY=~/mpy/mpy-cross
  - URL=https://github.com/micropython/micropython.git
  - if [ ! -d $MPY ]; then git clone -b v1.14 $URL ~/mpy; fi
  - make -C $MPY
  - export PATH=$PATH:$MPY
  - inv health

script:
  # quick native checks
  - pio run -e native -s
  - mpy-cross valid/hello.py
  - .pio/build/native/program valid/hello.mpy
  - pio test -e native

  # FIXME native invoke tasks
  - rm -rf .pio
  - inv -e native
  - inv -e python
