# see https://docs.platformio.org/en/latest/integration/ci/travis.html

dist: focal
language: python
python:
    - "3.9"

sudo: false
cache:
    directories:
        - $HOME/.platformio
        - $HOME/.cache/pip

install:
    - pip install -U platformio invoke
    - pio update

script:
    - pio run -e native
    - pio test -e native
    - inv native
    - inv python
