# see https://docs.platformio.org/en/latest/integration/ci/travis.html

dist: focal
language: python
python:
  - "3.8.5"

sudo: false
cache:
  pip: true
  directories:
    - $HOME/.platformio
    - $HOME/upy

install:
  - pip install -U platformio invoke
  - pio update
  - URL=https://github.com/micropython/micropython.git
  - if [ ! -d $HOME/upy ]; then echo yes $URL; else echo no $URL; fi
  - if [ ! -d $HOME/upy ]; then git clone --depth 1 -b v1.13 $URL $HOME/upy; fi
  - make -C $HOME/upy/mpy-cross/
  - export PATH=$PATH:$HOME/upy/mpy-cross

script:
  - pio run -e native
  - .pio/build/native/program
  - pio test -e native
  - inv -l
  - inv native
  - inv python
