# see https://docs.platformio.org/en/latest/integration/ci/travis.html

dist: focal
language: generic

sudo: false
cache:
  pip: true
  directories:
    - $HOME/.platformio
    - $HOME/mpy

install:
  - pip install -U platformio invoke
  - pio upgrade
  - pio update
  - MPY=https://github.com/micropython/micropython.git
  - if [ ! -d ~/mpy/mpy-cross ]; then git clone --depth 1 -b v1.13 $MPY ~/mpy; fi
  - make -C ~/mpy/mpy-cross/
  - export PATH=$PATH:$HOME/mpy/mpy-cross
  - pio system info
  - inv health

script:
  - pio run -e native -v
  - mpy-cross valid/hello.py
  - .pio/build/native/program valid/hello.mpy
  - pio test -e native
  - rm -rf .pio
  - inv -e native
  - inv -e python
