# using Ubuntu 20.04 and the generic image, which has Python w/o virtualenv

dist: focal
language: generic

sudo: false
cache:
  pip: true
  directories:
    - $HOME/.platformio
    - $HOME/mpy

install:
  - pip3 --version
  - pip3 install -U platformio invoke
  - pio update
  - pio system info

  - MPY=~/mpy/mpy-cross
  - GIT=https://github.com/micropython/micropython.git
  - if [ ! -d $MPY ]; then git clone --depth 1 -b v1.14 $GIT ~/mpy; fi
  - make -C $MPY
  - export PATH=$PATH:$MPY

script:
  - inv health
  - pio run -e native -s
  - mpy-cross valid/hello.py
  - .pio/build/native/program valid/hello.mpy

  - pio test -e native

  - rm -rf .pio
  - inv -e native
  - inv -e python
