# make-based TDD runner for C++ - this makefile uses tdd.py and fswatch

ROOT = ../..
LIBS = $(ROOT)/common
DIRS = monty
OPTS = -Wall -Wextra -DDOCTEST -DDOCTEST_CONFIG_TREAT_CHAR_STAR_AS_STRING \
	   -I$(ROOT)/libext/doctest/doctest

include $(ROOT)/scripts/native.mk
