# make-based TDD runner for C++ - this makefile uses tdd.py and fswatch

ROOT = ../..
LIBS = $(ROOT)/src
DIRS = monty
OPTS = -Wall -Wextra -DDOCTEST -DDOCTEST_CONFIG_TREAT_CHAR_STAR_AS_STRING \
	   -I$(ROOT)/import/doctest/doctest

include $(ROOT)/tools/native.mk
